### ISSUE TITLE
Tweet Cell Layout issue

### ISSUE THREAD

**Issue by mltbnz** [criticalmaps/criticalmaps-ios#105]
Handle label slips under dateLabel
![8A4DCAE2-EFEE-4CE1-B936-2635A00143B0](https://user-images.githubusercontent.com/14075359/59792245-010f1b00-92d4-11e9-9488-e55aced12bff.jpeg)

**Comment by zeitschlag** [comment]
Hi, I wanted to have a look at this, as it's labeled with `good first issue`, but to me it looks like [you already fixed this](https://github.com/criticalmaps/criticalmaps-ios/commit/5e97bdb4f10762e5308e649baa838b8775de7cd5)?

![Screen Shot 2019-09-22 at 10 04 12](https://user-images.githubusercontent.com/2580019/65384252-6124bb80-dd20-11e9-8aec-dd219adbe9cd.png)

**Comment by mltbnz** [comment]
I think you are right. I haven't seen it since.
Will close this one. 🙏
