### ISSUE TITLE
iOS 13 Support

### ISSUE THREAD

**Issue by lennet** [criticalmaps/criticalmaps-ios#113]
## Modal presentations

iOS 13 has a new default modal transition.

![modal](https://user-images.githubusercontent.com/7677738/60342407-ab143480-99b1-11e9-8f87-f0b9af553b01.gif) 

Do we need some design changes here @zutrinken . Using the old full screen presentation would also be possible

## Colors - Darkmode 

Our Theming/ Darkmode implementation breaks for some components. Maybe we should adopt to the system Darkmode for iOS 13 Users.
<img width="456" alt="Bildschirmfoto 2019-06-28 um 14 33 36" src="https://user-images.githubusercontent.com/7677738/60342432-b9fae700-99b1-11e9-9794-ac12d502a12d.png">
<img width="456" alt="Bildschirmfoto 2019-06-28 um 14 33 25" src="https://user-images.githubusercontent.com/7677738/60342450-c121f500-99b1-11e9-9a36-54ef424d0104.png">

## Swift Package Manager

It would be nice in my opinion to replace our current dependency manager cocoapods with the Swift Package Manager that is built into Xcode 11. That would allow us to build the project without needing any additional tooling

**Comment by zutrinken** [comment]
New modal looks good. One detail is the background color behind the map. Would make it black to see some depth.

**Comment by mltbnz** [comment]
I would love to adopt the dark mode to native support

**Comment by lennet** [comment]
<img width="386" alt="Bildschirmfoto 2019-08-10 um 09 26 16" src="https://user-images.githubusercontent.com/7677738/62819117-f5600800-bb50-11e9-8aed-73f12aee72d8.png">
 
Thats how the chat / twitter control looks like with the current beta @zutrinken

**Comment by mltbnz** [comment]
I noticed that the navigationBar in the socialcontroller looks the same on `develop`. In the designs it is never translucent but we set it to be in the light mode. Was that by mistake?
