### ISSUE TITLE
Increase Contrast support 

### ISSUE THREAD

**Issue by lennet** [criticalmaps/criticalmaps-ios#127]
It would be nice to support the increase contrast feature of iOS. 

We could do that by listening to https://developer.apple.com/documentation/uikit/uiaccessibility/1615087-isdarkersystemcolorsenabled to change the colors or use asset catalog but that only works on iOS 13 +

**Comment by pankova** [comment]
Hello! 🙂 Could I help you with it as Hacktoberfest participating?

**Comment by mltbnz** [comment]
Since the app now uses `SwiftUI`: 
https://developer.apple.com/documentation/swiftui/environmentvalues/colorSchemeContrast which has a [`increased`](https://developer.apple.com/documentation/swiftui/colorschemecontrast/increased) value that indicates the increases contrast mode
