### ISSUE TITLE
Open Twitter on tapping tweet

### ISSUE THREAD

**Issue by lennet** [criticalmaps/criticalmaps-ios#129]

**Comment by maxxx777** [comment]
What's wrong with opening Twitter? it works correctly for me.

**Comment by lennet** [comment]
For me it only works on tapping a link. I would like to see the tweet on the Web or in the app on tapping anywhere (except for the links)

**Comment by maxxx777** [comment]
thanks, got it. I thought it's about Twitter link on the settings screen.

**Comment by maxxx777** [comment]
@lennet what I noticed
- some tweets don't contain url, for example:
```
urls: [ ]
```
- some tweets may contain not a twitter link, but some other place
for example:
```
urls: [
{
  url: "https://t.co/2IB9lpYbxM",
  expanded_url: "https://github.com/criticalmaps/criticalmaps-ios",
  display_url: "github.com/criticalmaps/c…"
}
]
```
- also some tweets could contain several links in the text.

so should we modify API response to add `tweet_url` field in JSON?
or should we just take the last link from `urls` array if it exists and open it, and if `urls` array is empty, don't open twitter tapping on it?

**Comment by lennet** [comment]
The API directly returns the response. from Twitter so there isn't much we can add https://github.com/criticalmaps/criticalmaps-api/blob/master/routes/twitter.js . Maybe it's possible to generate a link with a given id

**Comment by maxxx777** [comment]
Thanks for the suggestion. Indeed it's possible to generate a link with user name and message id.
