### ISSUE TITLE
Script for updating our dependencies 

### ISSUE THREAD

**Issue by lennet** [criticalmaps/criticalmaps-ios#142]
It would be nice to have a script to update all our dependencies such as
- bundle update and bundle exec 
- fastlane snapshot update
- license-plist
- swiftformat

**Comment by mltbnz** [comment]
I recently made some good experience with Rake scripts. Could add that

**Comment by raviTokopedia** [comment]
@mltbnz are you working on this? @lennet Are all these actions supposed to be in a single script?

**Comment by mltbnz** [comment]
I didn’t start working on it. Feel free to kick it off. 
If you are starting on this it is probably a good idea to do a draft pull request with the wip so it is visible that somebody is working on this

**Comment by lennet** [comment]
Hi @raviTokopedis, Thank you for contributing!

Yes, one script that triggers all these update commands would be awesome.

**Comment by Ravi61** [comment]
@lennet Added PR #146 for this
