### ISSUE TITLE
Dynamic poll rate

### ISSUE THREAD

**Issue by lennet** [criticalmaps/criticalmaps-ios#143]
We are currently updating the Apps content every 12 seconds or after the user send a message as it's using the same API. This may result in an outdated map especially if a request failed because we are currently waiting another 12 seconds for the next try at which point the app might already be in the background. 

It would be nice to be smarter about updating the poll the data every 6 seconds if the app is in foreground and every 12 seconds in background (maybe as well in lower power/ data mode ?). Additionally we should retry sooner, if possible as soon as possible (maybe check for internet connection on iOS 12+ devices https://developer.apple.com/documentation/network/nwpathmonitor)

**Comment by iglushchuk** [comment]
Hi, I would like to make this task, may I?

I have looked at RequestManager, so I think that we can poll the data every 6 seconds and for background update run `application(_:performFetchWithCompletionHandler:)` and BGAppRefreshTask (depends on iOS version)

By the way method `updateData()` might be wrapped to asynchronous operation. It seems that it would be easier to control update, when we have queue.

What do you think, @lennet ?
