### ISSUE TITLE
Friends Feature - Tap to dismiss name editing

### ISSUE THREAD

**Issue by lennet** [criticalmaps/criticalmaps-ios#162]
<img width="164" alt="Bildschirmfoto 2019-10-19 um 10 16 06" src="https://user-images.githubusercontent.com/7677738/67140296-788c9100-f259-11e9-9857-3477aac8d65d.png">

It would be nice if its possible to dismiss the keyboard after editing the name on tapping anywhere on the screen instead of just the return key. We had that already implemented but removed it because the old implementation conflicted with the tableviews cell selection.

All the work friends feature can be found in the Friends feature branch

**Comment by lennet** [comment]
Editing currently crashes but it should work again after https://github.com/criticalmaps/criticalmaps-ios/pull/161 got merged

**Comment by besilva** [comment]
Can I work on this issue?

**Comment by lennet** [comment]
Hey @besilva, Sure, we appreciate support on any issue! You can open a draft pr and link it against the issue to show other contributors that you are working on the issue

**Comment by besilva** [comment]
Done it
