### ISSUE TITLE
Friends Feature - Night mode support 

### ISSUE THREAD

**Issue by lennet** [criticalmaps/criticalmaps-ios#163]
This is how it currently looks like with night mode enabled
<img width="504" alt="Bildschirmfoto 2019-10-19 um 10 19 39" src="https://user-images.githubusercontent.com/7677738/67140361-0c5e5d00-f25a-11e9-88fa-b1fd05ca5909.png">

And this how it should look like:
<img width="152" alt="Bildschirmfoto 2019-10-19 um 10 20 45" src="https://user-images.githubusercontent.com/7677738/67140372-2009c380-f25a-11e9-8b4b-c2d2388a3122.png">

More details can be found in the Design repo http://github.com/criticalmaps/criticalmaps-design
Also the friends indicator on the map should update it's color in night mode 

All the work friends feature can be found in the Friends feature branch.

**Comment by mltbnz** [comment]
🤘

**Comment by besilva** [comment]
Done it

**Comment by fbernutz** [comment]
This is done and can be found in this PR: https://github.com/criticalmaps/criticalmaps-ios/pull/204
