### ISSUE TITLE
Friends Feature - UITests

### ISSUE THREAD

**Issue by lennet** [criticalmaps/criticalmaps-ios#164]
It would be nice to have UITests for testing the full flow of adding a friend through opening a link (example link: criticalmaps:follow?token=TestKey&name=TestName) and deleting it afterwards in the friends view.

All the work friends feature can be found in the Friends feature branch

**Comment by besilva** [comment]
Can I work on this?

**Comment by fbernutz** [comment]
@besilva Do you still want to work on that? 

The setup for working with the Friends feature changed a bit. 
The Friends feature is already merged on `master` but hidden with a feature toggle. To activate the feature toggle, you could use a new launch argument like `ACTIVATE_FRIENDS` in the UITest similar to the existing `SKIP_ANIMATIONS`. In the `AppDelegate.swift` you could activate the feature toggle when the specific launch argument is set.

```swift
if ProcessInfo.processInfo.arguments.contains("ACTIVATE_FRIENDS") {
    var feature = Feature.friends
    feature.isActive = true
}
```

With this setup you can ensure that the feature toggle is activated in the UITest.
