### ISSUE TITLE
Bug: Swipe Down Gesture in Modal changes Content

### ISSUE THREAD

**Issue by fbernutz** [criticalmaps/criticalmaps-ios#171]
**Current Behaviour**
When you swipe a bit down in the `SocialViewController`, but don't dismiss the modal with the swipe down gesture, the content of the view changes but the selected segmented control index stays the same. 

![dismiss](https://user-images.githubusercontent.com/26111180/67306489-57e16700-f4f7-11e9-979e-108ba8976c93.gif)

**Expected Behaviour**
When you don't dismiss the modal, the content should stay the same.

**Comment by mltbnz** [comment]
Do you get that behavior in the develop  branch version or AppStore?

**Comment by fbernutz** [comment]
Both.

**Comment by mltbnz** [comment]
Interesting because for me it works fine

**Comment by lennet** [comment]
I can reproduce it on iOS 13.1.3

**Comment by fbernutz** [comment]
Oh wow, yeah, I am on iOS 13.1.3 as well. I was also wondering why viewWillAppear is called with this gesture. Maybe we should keep that in mind and it will change again in some future iOS versions...

**Comment by lennet** [comment]
https://twitter.com/arekholko/status/1137756105050918912?s=20
