### ISSUE TITLE
Chat should not be able to send whitespace

### ISSUE THREAD

**Issue by mltbnz** [criticalmaps/criticalmaps-ios#173]
My idea for the fix: Adding whitespace in the chat should enable the send button but if only whitespace has been added the send event should not trigger the post request.

**Comment by lennet** [comment]
I think It should only be enabled if its a valid message which we should post to the server. 

Maybe worth adding UITests/ since it regressed multiple times

**Comment by mltbnz** [comment]
Ok with both. UI Test since there are no ViewModels or such where we could test against

**Comment by mltbnz** [comment]
I think it actually did not regress since the check just covered `isEmpty`
