### ISSUE TITLE
Rules Detail view isn't readable in Dark mode 

### ISSUE THREAD

**Issue by lennet** [criticalmaps/criticalmaps-ios#174]
![image_from_ios](https://user-images.githubusercontent.com/7677738/67311050-210f4f00-f4ff-11e9-8a93-6452547a5f4a.png)

This is a regression probably caused by #132 

This is how the text color should look like 
<img width="267" alt="Bildschirmfoto 2019-10-22 um 19 08 01" src="https://user-images.githubusercontent.com/7677738/67311119-4603c200-f4ff-11e9-8603-ad4567e64220.png">

more details in the design repo http://github.com/criticalmaps/criticalmaps-design

We are currently using UITextView with attributed attachments which makes the configuration overly complicated. Maybe worth migrating to a UIStackView and a plain UIImageView + UILabel while fixing the bug

**Comment by mltbnz** [comment]
#176
