### ISSUE TITLE
The action indicator is hardly visible in Dark Mode

### ISSUE THREAD

**Issue by lennet** [criticalmaps/criticalmaps-ios#175]
Observed:
![image](https://user-images.githubusercontent.com/7677738/67311356-b3afee00-f4ff-11e9-85b7-c1893b436715.png)

This is how it should look like

<img width="248" alt="Bildschirmfoto 2019-10-22 um 19 11 35" src="https://user-images.githubusercontent.com/7677738/67311420-d80bca80-f4ff-11e9-9d44-e2937f6ff366.png">

More infos in the design repo  http://github.com/criticalmaps/criticalmaps-design

**Comment by fbernutz** [comment]
This is also an issue on RulesViewController. Fixed in #248 👍
