### ISSUE TITLE
Change color of map marker

### ISSUE THREAD

**Issue by zutrinken** [criticalmaps/criticalmaps-ios#181]
In preparation of the friends feature all regular participants should be shown in a more subtle style.

<table>
<tr>
<td>
<img src="https://user-images.githubusercontent.com/888679/67720445-30e1d400-f9d4-11e9-8fd4-10d2d1d484af.png" />
</td>
<td>
<img src="https://user-images.githubusercontent.com/888679/67720442-2d4e4d00-f9d4-11e9-9ac8-10a4604e63b6.png" />
</td>
</tr>
</table>

**Comment by mltbnz** [comment]
#241
