### ISSUE TITLE
Appearance settings

### ISSUE THREAD

**Issue by zutrinken** [criticalmaps/criticalmaps-ios#182]
Add "use system preferences" as an appearance option. With this setting the app can benefit from the automatic switch function on sunset.

<table>
<tr>
<td>
<img src="https://user-images.githubusercontent.com/888679/67723328-f2501780-f9db-11e9-834e-e902575be08e.png" />
</td>
<td>
<img src="https://user-images.githubusercontent.com/888679/67723327-f2501780-f9db-11e9-92f4-99db4ad7c52e.png" />
</td>
</tr>
</table>

**Comment by lennet** [comment]
It might be helpful to cherry pick SetttingsViewController and SettingsSection from the Friends feature branch as it adds support for navigating to view controllers from settings which is needed for the transition for the  Appearance Settings.

**Comment by mltbnz** [comment]
What should the app present when the OS is < 13?

**Comment by lennet** [comment]
Wasn't the idea to migrate to the official API at some point and remove dark mode support for pre iOS 13?

**Comment by mltbnz** [comment]
Would make the code nicer but unsure if removing functionality from pre ios 13 users is a good idea

**Comment by lennet** [comment]
Yes, that's true, but still an option we should keep in mind. Especially because our custom solution becomes harder to maintain over time and also more user upgrade to iOS 13

**Comment by mltbnz** [comment]
I am totally up for it but since the current min deployment target is 10. .. removing something that has been a part of the app since some time is not needed. The solution that is in the app is definitely hard to maintain already especially when adding new UI. 

Right now I would only remove the current implementation if the min deployment target is iOS 13

**Comment by lennet** [comment]
How about using something like that https://github.com/microsoft/FluentDarkModeKit, that also requires dropping iOS 10. Also looks super similar to the official API, so once we our target is iOS 13, migrating to the official API shouldn't be a lot of work

**Comment by zutrinken** [comment]
Does supporting < 13 also include native dark mode maps or only the UI? If native dark mode map isn't included I'd drop the support.

**Comment by lennet** [comment]
For pre iOS 13 we are using custom dark map tiles 
<img width="582" alt="Bildschirmfoto 2020-03-25 um 20 04 11" src="https://user-images.githubusercontent.com/7677738/77575529-f5d8c380-6ed3-11ea-901d-6e2208e6b9ee.png">

**Comment by mltbnz** [comment]
It’s so dark

**Comment by Freelenzer** [comment]
Hi, I added a first implementation of improved appearance settings.
The idea was to keep the switch on iOS < 13 and add the advanced option on iOS >= 13. 
If you approve I can implement the feature completely.

I hope I didn't took this issue from any "Hacktoberfest" plannings :(

**Comment by fbernutz** [comment]
> Hi, I added a first implementation of improved appearance settings.
> The idea was to keep the switch on iOS < 13 and add the advanced option on iOS >= 13.
> If you approve I can implement the feature completely.
> 
> I hope I didn't took this issue from any "Hacktoberfest" plannings :(

I think your idea is a great solution, so we won't cut any features for < iOS 13 users and add the advanced option for >= iOS 13.
