### ISSUE TITLE
Use Icon instead of text for send button in Chat

### ISSUE THREAD

**Issue by lennet** [criticalmaps/criticalmaps-ios#186]
<table><tr><td><img src="https://user-images.githubusercontent.com/888679/67808811-a662a880-fa97-11e9-8332-79b8730346c7.png" /></td><td><img src="https://user-images.githubusercontent.com/888679/67808810-a662a880-fa97-11e9-822d-2537afc49692.png" /></td></tr></table>

_Originally posted by @zutrinken in https://github.com/criticalmaps/criticalmaps-ios/pull/178#issuecomment-547627974_

**Comment by lennet** [comment]
@zutrinken can you attach the exported assets in 1x, 2x and 3x to the issue when they are ready?

**Comment by zutrinken** [comment]
I'd suggest to build it without explicit assets and handling colors via code. Here's the send icon as vector: [icon-send.pdf](https://github.com/criticalmaps/criticalmaps-ios/files/3785870/icon-send.pdf) (only the error) ... Does this work?

**Comment by lennet** [comment]
Thanks! That should work
