### ISSUE TITLE
The App is crashing on iOS 12

### ISSUE THREAD

**Issue by lennet** [criticalmaps/criticalmaps-ios#189]
The crash is 100% reproducible on iOS 12 after opening the chat or twitter.

Seems to be related to a bug in Xcode 11.2 and can be resolved by initialising UITextViews in pure code instead of using Xibs https://stackoverflow.com/questions/58657087/after-upgrading-to-xcode-11-2-from-xcode-11-1-app-crashes-due-to-uitextlayoutv

CriticalMaps[17919:2694235] *** Terminating app due to uncaught exception 'NSInvalidUnarchiveOperationException', reason: 'Could not instantiate class named _UITextLayoutView because no class named _UITextLayoutView was found; the class needs to be defined in source code or linked in from a library (ensure the class is part of the correct target)'
*** First throw call stack:
(
0 CoreFoundation 0x00000001020e58db __exceptionPreprocess + 331
1 libobjc.A.dylib 0x0000000101684ac5 objc_exception_throw + 48
2 CoreFoundation 0x00000001020e5735 +[NSException raise:format:] + 197
3 UIFoundation 0x000000010b2866c9 UINibDecoderDecodeObjectForValue + 360
4 UIFoundation 0x000000010b286af9 UINibDecoderDecodeObjectForValue + 1432
5 UIFoundation 0x000000010b286554 -[UINibDecoder decodeObjectForKey:] + 251
6 UIKitCore 0x0000000108494c4d -[UIView initWithCoder:] + 802
7 UIKitCore 0x0000000108438f4d -[UIScrollView initWithCoder:] + 68
8 UIKitCore 0x000000010833850d -[UITextView initWithCoder:] + 65
9 CriticalMaps 0x000000010033376d $s12CriticalMaps22LinkResponsiveTextViewC5coderACSgSo7NSCoderC_tcfc + 141
10 CriticalMaps 0x0000000100333833 $s12CriticalMaps22LinkResponsiveTextViewC5coderACSgSo7NSCoderC_tcfcTo + 51
11 UIKitCore 0x0000000107c64861 -[UIClassSwapper initWithCoder:] + 246
12 UIFoundation 0x000000010b286852 UINibDecoderDecodeObjectForValue + 753
13 UIFoundation 0x000000010b286af9 UINibDecoderDecodeObjectForValue + 1432
14 UIFoundation 0x000000010b286554 -[UINibDecoder decodeObjectForKey:] + 251
15 UIKitCore 0x0000000108494c4d -[UIView initWithCoder:] + 802
16 UIKitCore 0x00000001081c35c7 -[UITableViewCellContentView initWithCoder:] + 42
17 UIFoundation 0x000000010b286852 UINibDecoderDecodeObjectForValue + 753
18 UIFoundation 0x000000010b286af9 UINibDecoderDecodeObjectForValue + 1432
19 UIFoundation 0x000000010b286554 -[UINibDecoder decodeObjectForKey:] + 251
20 UIKitCore 0x0000000108494c4d -[UIView initWithCoder:] + 802
21 UIKitCore 0x00000001081afb21 -[UITableViewCell initWithCoder:] + 85
22 CriticalMaps 0x0000000100351865 $s12CriticalMaps18TweetTableViewCellC5coderACSgSo7NSCoderC_tcfc + 1285
23 CriticalMaps 0x0000000100351943 $s12CriticalMaps18TweetTableViewCellC5coderACSgSo7NSCoderC_tcfcTo + 51
24 UIKitCore 0x0000000107c64861 -[UIClassSwapper initWithCoder:] + 246
25 UIFoundation 0x000000010b286852 UINibDecoderDecodeObjectForValue + 753
26 UIFoundation 0x000000010b286554 -[UINibDecoder decodeObjectForKey:] + 251
27 UIKitCore 0x0000000107c68ef3 -[UIRuntimeConnection initWithCoder:] + 136
28 UIFoundation 0x000000010b286852 UINibDecoderDecodeObjectForValue + 753
29 UIFoundation 0x000000010b286af9 UINibDecoderDecodeObjectForValue + 1432
30 UIFoundation 0x000000010b286554 -[UINibDecoder decodeObjectForKey:] + 251
31 UIKitCore 0x0000000107c667cd -[UINib instantiateWithOwner:options:] + 1216
32 UIKitCore 0x0000000108207d1e -[UITableView _dequeueReusableViewOfType:withIdentifier:] + 613
33 CriticalMaps 0x00000001002f2e64 $sSo11UITableViewC12CriticalMapsE19dequeueReusableCell6ofTypexxm_tSo0abG0CRbzlF + 164
34 CriticalMaps 0x0000000100357238 $s12CriticalMaps27MessagesTableViewControllerC05tableE0_12cellForRowAtSo07UITableE4CellCSo0lE0C_10Foundation9IndexPathVtF + 280
35 CriticalMaps 0x00000001003573e5 $s12CriticalMaps27MessagesTableViewControllerC05tableE0_12cellForRowAtSo07UITableE4CellCSo0lE0C_10Foundation9IndexPathVtFTo + 165
36 UIKitCore 0x000000010825eb6a -[_UIFilteredDataSource tableView:cellForRowAtIndexPath:] + 95
37 UIKitCore 0x0000000108222f60 -[UITableView _createPreparedCellForGlobalRow:withIndexPath:willDisplay:] + 764
38 UIKitCore 0x0000000108223499 -[UITableView _createPreparedCellForGlobalRow:willDisplay:] + 73
39 UIKitCore 0x00000001081eb654 -[UITableView _updateVisibleCellsNow:isRecursive:] + 2870
40 UIKitCore 0x000000010820b76b -[UITableView layoutSubviews] + 165
41 UIKitCore 0x00000001084c5e69 -[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 1417
42 QuartzCore 0x0000000103615d22 -[CALayer layoutSublayers] + 173
43 QuartzCore 0x000000010361a9fc _ZN2CA5Layer16layout_if_neededEPNS_11TransactionE + 396
44 QuartzCore 0x0000000103626d58 _ZN2CA5Layer28layout_and_display_if_neededEPNS_11TransactionE + 72
45 QuartzCore 0x000000010359624a _ZN2CA7Context18commit_transactionEPNS_11TransactionE + 328
46 QuartzCore 0x00000001035cd606 _ZN2CA11Transaction6commitEv + 610
47 QuartzCore 0x00000001035cdeb2 _ZN2CA11Transaction17observer_callbackEP19__CFRunLoopObservermPv + 76
48 CoreFoundation 0x000000010204c2c7 CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION + 23
49 CoreFoundation 0x000000010204678e __CFRunLoopDoObservers + 430
50 CoreFoundation 0x0000000102046e01 __CFRunLoopRun + 1505
51 CoreFoundation 0x00000001020464d2 CFRunLoopRunSpecific + 626
52 GraphicsServices 0x000000010af2a2fe GSEventRunModal + 65
53 UIKitCore 0x0000000107fe6fc2 UIApplicationMain + 140
54 CriticalMaps 0x00000001002d38fb main + 75
55 libdyld.dylib 0x000000010579d541 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by lennet** [comment]
We might also rollback to Xcode 11.1 and wait for an updated version that contains a fix

**Comment by mltbnz** [comment]
I am still using 11.1. Works as expected. Also not sure if this should be an issue since it is clearly an XCode Bug

**Comment by lennet** [comment]
Makes sense. Let’s keep this one as an reminder that we shouldn’t use Xcode 11.2 for shipping a release build until a newer version of Xcode that fixes that issues is available

**Comment by brunomunizaf** [comment]
FYI - Apple just released a version of Xcode to specifically fix this issue.

**Comment by mltbnz** [comment]
Also reminds me that we should get git flow going probably. ATM we mehr everything to master which could improve by using the develop branch for the latest work and then merge to master for releases. Merge to master could maybe then also trigger an AppStore release but might not suit an open source repo. Merge to develop though could definitely trigger a TestFlight build. Think we could use Fastlane match. Definitely one of the things on my want to do list

**Comment by mltbnz** [comment]
Having master release a new version would have the benefit that we could pin the Xcode version in the CI I think

**Comment by lennet** [comment]
@mltbnz Lets track that in a separate issue
