### ISSUE TITLE
Only reload cells that changed for MessagesTableViewController

### ISSUE THREAD

**Issue by lennet** [criticalmaps/criticalmaps-ios#190]
https://github.com/criticalmaps/criticalmaps-ios/blob/600f0853a6d30ea135ab5247fa04c281fec159e8/CriticalMass/MessagesTableViewController.swift#L29

We are currently just calling `reloadData` if we receive new message objects which is not super efficient. It would be nice if we would just update the rows that were inserted, deleted or updated.

**Comment by iglushchuk** [comment]
Hi! I can handle it

**Comment by lennet** [comment]
Cool!

**Comment by iglushchuk** [comment]
Hi! I really apologise, that I didn't resolve that problem, recently I was really busy. Now I have time and I'd like to fix that issue in the near future :)
I have investigated how to solve this issue, I understand now how it can be fixed. Also I have a question: what do you think if we use new diffable datasource for iOS 13 and for iOS 10-12 we will keep reloadData?

**Comment by lennet** [comment]
No worries! 

Sounds like a good Idea to me!
