### ISSUE TITLE
Next ride info

### ISSUE THREAD

**Issue by zutrinken** [criticalmaps/criticalmaps-ios#194]
Show an info box for the next ride nearby, based on the [criticalmass.in](https://criticalmass.in) API.
* The most nearby event is shown by a special marker.
* Tab on info box centers map on event location.
* Info box and marker disappear 30min after the start of current event.
* Info box and marker for the next event appear 8h after the start of previous event.

<table><tr><th>Light</th><th>Dark</th></tr><tr><td>
<img src ="https://user-images.githubusercontent.com/888679/68546887-d2592480-03db-11ea-8d4c-2f8deea8adbf.png" /></td><td><img src ="https://user-images.githubusercontent.com/888679/68546888-d2592480-03db-11ea-8311-091c9e47e0bc.png" /></td></tr></table>

**Comment by mltbnz** [comment]
Maybe the feature could also get its own tab where we could mirror some of the functionality from httpss://criticalmass.in/
Maybe on the Map the App can Show the next Mass closest to your coordinate. Therefore the api would need an endpoint to do so. 
The tab could also have the option to add new made to the Database

**Comment by maltehuebner** [comment]
I’m already working on it in https://github.com/calderacc/criticalmass-in/pull/567

The endpoint will allow you to create complex queries for dates and cities and of cource you may limit the results to a bounding box or a radius around a provided coordinate.

**Comment by maltehuebner** [comment]
Okay, it took me some more days, but most of the api is now covered by tests and it looks like it’s working now: https://criticalmass.in/api/doc

Please have a look at it and tell me if it’s useful for you.

**Comment by lennet** [comment]
I think we might start with a simple first version as presented by @zutrinken and iterate instead of starting a big project that’s hard to finish. Is the design spec final enough to create smaller issues for the feature ?
