### ISSUE TITLE
ability to use a custom api server

### ISSUE THREAD

**Issue by derhuerst** [criticalmaps/criticalmaps-ios#20]
Hey!

I'd like to (ab)use this wonderful app for hitchhiking, for this purpose it would make sense to run a custom server. What do you think about adding a hidden way to change the API server address?

**Comment by stephanlindauer** [comment]
I think this is a feature so far back in our list, that it will probably not get in. But if you tell us what you need this for, we could maybe find a way to implement that use-case.
Also there is always the option to compile the app with your custom server url.

**Comment by derhuerst** [comment]
i'd primarily use it for

- hitchhiking, to let others know where I am. i might also expand this to a map where all hitchhikers can see each other
- street protests, to find where the crowd currently is, to estimate the number of participants

**Comment by stephanlindauer** [comment]
don't you rather want to improve the existing backend?

**Comment by derhuerst** [comment]
In which way would that be an improvement of the backend? I want to have a completely separate pool of devices, so I'd just redeploy the backend somewhere.

**Comment by stephanlindauer** [comment]
you could introduce labels or groups, user can assign themselfs into.
i am pretty sure that adding a feature to replace the backend url is something you would have to implement yourself due to other priorities we have atm.

**Comment by derhuerst** [comment]
> you could introduce labels or groups, user can assign themselfs into.

I'm pretty sure that the main Critical Mass backend wouldn't benefit from having my position when hitchhiking somewhere in the world. Also, I wouldn't like that others (except friends) can tell where I am.

> i am pretty sure that adding a feature to replace the backend url is something you would have to implement yourself due to other priorities we have atm.

Okay, if you stay with this position, I will close the issue. But keep in mind that the concept of an app like this would be useful in general.
