### ISSUE TITLE
Feature flagging

### ISSUE THREAD

**Issue by lennet** [criticalmaps/criticalmaps-ios#203]
We have some difficulties currently to maintain the Friends feature branch. It would be nice to have a small light weight figure flagging component that would allow us to merge the Friends feature in to the master branch without being available in a production environment

**Comment by fbernutz** [comment]
@lennet Should the feature be activated/deactivated within the app dynamically (so we would need a UI for that with a secret menu or something) or is it enough to activate/deactivate the feature in code and then run the app with the configuration?

**Comment by lennet** [comment]
Dynamically setting the Feature flag would be nice to have but not required. A static system in code should be fine for now
