### ISSUE TITLE
Rework app data flow to move away from NSNotification based flow

### ISSUE THREAD

**Issue by mltbnz** [criticalmaps/criticalmaps-ios#245]
The apps data flow heavily uses NSNotification to pass objects around which I think is not a good way of passing data through the app. 

### LocationManager
* should be reworked to be injected in objects that use location
* should not publish `Location` object and instead publish `CLLocation`. Location can be created when needed.
* Auth status could be an observable

### ApiResponse
* could be passed via closure or something other but not via Notifications and the casting

**Comment by lennet** [comment]
Thanks for starting the conversation! This is important and something I wanted to do for a while but never started working on it. 

Small comments about the `Location` Object. The name Location is super misleading and originally comes from the API response object and just reused that. But in fact it’s should be called `Rider` or something similar. It also contains more properties than just coordinates

**Comment by mltbnz** [comment]
It’s not just about the type but the data flow of a lot of modules. Renaming Location to something more self explaining could be on of the tasks though 😀

Wanted to have this issue to link PRs to it and we could also discuss what kind of solutions to use for the different needs of components/controller

**Comment by mltbnz** [comment]
@lennet @fbernutz 
What do you think if we bump the deployment target to iOS 13?

* we could then remove the whole weird darkMode code
* and we could rewrite the app data flow to use combine

we would loose a couple of phones but I would say most users are already on iOS 13

**Comment by lennet** [comment]
I‘m okay with dropping iOS 10 and maybe 11 if there are APIs that require it. That would also allow use to migrate to xcassetcatalog for color and clean up the dark mode code.

But I‘m not sure about dropping 12 because there are a devices that can‘t update to iOS 13 that are still in use

**Comment by fbernutz** [comment]
I don't know how many users use iOS 12 or lower... Can't decide if it's worth it 🤔

**Comment by lennet** [comment]
Not sure if https://github.com/OpenCombine/OpenCombine might be an option for pre iOS 13

**Comment by lennet** [comment]
<img width="987" alt="Bildschirmfoto 2020-07-22 um 17 38 52" src="https://user-images.githubusercontent.com/7677738/88197107-4c67cb80-cc42-11ea-8f87-0809c6613ed9.png">

That are the installs in the last 90 days. Looks like there are still many iOS 12. Interestingly, none with iOS 11 but a few with iOS 10.

**Comment by mltbnz** [comment]
> Not sure if https://github.com/OpenCombine/OpenCombine might be an option for pre iOS 13

That's also nice

**Comment by mltbnz** [comment]
So do we want to raise the target to 12? As a compromise we could branch of a iOS 10 deployment target branch that would not get updates? Just an idea. IMO we pile up tech dept when not adding more and more `if available`. On the other hand we do not want to be a second upper class Corona warn app ;)

**Comment by mltbnz** [comment]
How about doing a rewrite of the app in Flutter?!

**Comment by mltbnz** [comment]
will be resolved when merging back #409

**Comment by mltbnz** [comment]
closed by #409
