### ISSUE TITLE
Add criticalmass.in banner cell in settings

### ISSUE THREAD

**Issue by mltbnz** [criticalmaps/criticalmaps-ios#255]
To credit the https://criticalmass.in API which is used for #194 there should be a banner in the settings section which links to the website.

**Cell DESIGN**
![cell_design](https://user-images.githubusercontent.com/14075359/75956327-f32c1500-5eb7-11ea-9426-c90becfdd62f.png)

**Cell in ViewController**
![cell_design](https://user-images.githubusercontent.com/14075359/75956361-050db800-5eb8-11ea-9373-6cbf306354a2.png)

**Comment by lennet** [comment]
Would be nice if we could reuse `SettingsGithubTableViewCellTableViewCell`

**Comment by mltbnz** [comment]
Maybe @zutrinken you could provide the assets for this?

**Comment by lennet** [comment]
![banner cm](https://user-images.githubusercontent.com/7677738/76072615-9a807900-5f98-11ea-9061-f5f2244a1d36.png)
