### ISSUE TITLE
Improve Voice Control support 

### ISSUE THREAD

**Issue by lennet** [criticalmaps/criticalmaps-ios#263]
We could improve the Voice Control support by adding additional `accessibilityUserInputLabels` (https://developer.apple.com/documentation/objectivec/nsobject/3197989-accessibilityuserinputlabels) to some of the elements. 

Especially in settings we could add additional inout labels to Obersavtion Mode and the project cells (Github, CriticaMass.in)
![IMG_1704](https://user-images.githubusercontent.com/7677738/76163279-128ba200-6145-11ea-8e3f-837a3c9222d7.PNG)

**Comment by fbernutz** [comment]
Resolved with #330
