### ISSUE TITLE
Update Project to Xcode 11.4 and Swift 5.2

### ISSUE THREAD

**Issue by lennet** [criticalmaps/criticalmaps-ios#278]
We need to update 

- [ ] [.swift-version](https://github.com/criticalmaps/criticalmaps-ios/blob/master/.swift-version)
- [ ] Xcode reference in our CI Actions (Not sure if Github Actions already supports the new Xcode version though)
- [ ] manually update dependencies and run swift-format just in case something changed for 5.2

**Comment by fbernutz** [comment]
At the moment Xcode 11.3.1 is still the default. (see here: https://github.com/actions/virtual-environments/blob/master/images/macos/macos-10.15-Readme.md#xcode)

**Comment by fbernutz** [comment]
They've installed the release version of Xcode 11.4 on the machines, so I think we could start using Xcode 11.4, when we change this line to 11.4: https://github.com/criticalmaps/criticalmaps-ios/blob/master/.github/workflows/main.yml#L12
