### ISSUE TITLE
Small UI bug on selecting message cells

### ISSUE THREAD

**Issue by lennet** [criticalmaps/criticalmaps-ios#279]
![image](https://user-images.githubusercontent.com/7677738/77818239-305b7f80-70d1-11ea-8466-d0b97a77436b.png)

The labels background color shouldn’t be different than the cells background color on selection.

**Comment by fbernutz** [comment]
Does it even makes sense to select a cell? Maybe it would be better to make the cells not selectable at all...

**Comment by lennet** [comment]
Yeah, we just have to make sure that links are still tapable and tweets are still selectable since they share a lot of code
