### ISSUE TITLE
Fix flaky AnnotationControllerTest on CI

### ISSUE THREAD

**Issue by fbernutz** [criticalmaps/criticalmaps-ios#287]
The test case `CMAnnotationControllerTests.test_ControllerShouldRemoveAnnotationWhenRideStartedMoreThen30MinutesAgo()` fails on CI. Might be a timing issue and maybe more tolerance would help to make the test more stable. 

Jobs: 
- https://github.com/criticalmaps/criticalmaps-ios/runs/597488944
- https://github.com/criticalmaps/criticalmaps-ios/pull/285/checks?check_run_id=597464953

**Comment by mltbnz** [comment]
the logs are gone...
This one still an issue?

Must be related the the expectation I guess. These are flaky by default on CI is my feeling.

**Comment by fbernutz** [comment]
I'm not sure if this is still an issue. I would close this and we can open a new issue if it makes problems again.

**Comment by mltbnz** [comment]
Seems like they are still an issue.. I'll try to work on a fix
