### ISSUE TITLE
Reimplement Twitter integration in Swift

### ISSUE THREAD

**Issue by lennet** [criticalmaps/criticalmaps-ios#32]

**Comment by lennet** [comment]
The iOS app currently has a direct connection to Twitter and displays all tweets for the hashtag #CMBerlin. The Android app uses api.criticalmaps.net/twitter as far as I can see and shows tweets about criticalmaps.

Which of the two variants should be implemented?

cc @stephanlindauer @headione

**Comment by headione** [comment]
imo both variants are fine but let’s use the dedicated api endpoint like android, to keep it consistent. wdyt?

**Comment by stephanlindauer** [comment]
i also vote to keep it consistent to use the api endpoint. i think i implemented it like that because then we don't have to expose the twitter api token.
