### ISSUE TITLE
Legal button is behind other buttons

### ISSUE THREAD

**Issue by jacquealvesb** [criticalmaps/criticalmaps-ios#329]
The legal button is behind the other buttons, so we can't see it. Maybe putting it on the info section on settings would be a good option.

![IMG_1712](https://user-images.githubusercontent.com/5198967/94320951-a8154480-ff64-11ea-93c5-ae3dcf5ff0e5.PNG)

iPhone 7, iOS 14.0.1

**Comment by mltbnz** [comment]
fixed in #342
