### ISSUE TITLE
Fix some visual appearances

### ISSUE THREAD

**Issue by mltbnz** [criticalmaps/criticalmaps-ios#364]
![image](https://user-images.githubusercontent.com/14075359/98852839-94606780-2458-11eb-9d09-6f8cd9144dd2.png)

Need to fix accessory color

![image](https://user-images.githubusercontent.com/14075359/98852934-b5c15380-2458-11eb-96f3-6511da6fd349.png)

Need to fix appearance for text input

<img width="559" alt="Screenshot 2020-11-11 at 20 33 17" src="https://user-images.githubusercontent.com/14075359/98855983-2ff3d700-245d-11eb-8350-f204fb61278c.png">
under iOS 12 the event marker is wrongly tinted

**Comment by besilva** [comment]
Can I take this issue? @mltbnz

**Comment by besilva** [comment]
Where can I check the correct appearance for text input? Does the team use Figma or some other design tool?

**Comment by besilva** [comment]
Nvm I found https://github.com/criticalmaps/criticalmaps-design

**Comment by mltbnz** [comment]
> Where can I check the correct appearance for text input? Does the team use Figma or some other design tool?

The Text Input should behave like an OS one would I would say. I fear its appearance is set in one of the `ThemeController` selector calls  which grew a little bit out of control. But looks like it's fixed in your PR?!

**Comment by mltbnz** [comment]
The bug only appears in the light version

![image](https://user-images.githubusercontent.com/14075359/99180426-847da780-2726-11eb-9f2d-8fa562b8a6cf.png)

![image](https://user-images.githubusercontent.com/14075359/99180429-8ba4b580-2726-11eb-8cad-438091547bbe.png)

**Comment by besilva** [comment]
I think it's ok now with my PR
