### ISSUE TITLE
Showing users name on chats

### ISSUE THREAD

**Issue by SeungJunLee-Apple** [criticalmaps/criticalmaps-ios#372]
**[Feature Request]**
I think showing the user name at chatView which is at the second popoverView can make this app better.
![IMG_B758967C6929-1](https://user-images.githubusercontent.com/60959924/100083740-2c187980-2e8d-11eb-9277-973ac6458281.jpeg)

**Comment by LeanDerVorausdenkende** [comment]
I think this anonymity is on purpose and should stay like this.

**Comment by mltbnz** [comment]
The app doesn't know who it's users are and due to that we are unable to display any information about users
