### ISSUE TITLE
Crash on iOS 14.2.1

### ISSUE THREAD

**Issue by tobi3988** [criticalmaps/criticalmaps-ios#373]
At the moment my Critical Maps is crashing on startup. 
I have an iPhone 12 Pro with iOS 14.2.1.
Deleting the App and reinstall didn't help

**Comment by LeanDerVorausdenkende** [comment]
I have the same problem. I'm on iPhone SE (old one) and IOS 14.0.1. After installing Critical Maps v3.9.1, the app crashed every time I started it.

**Comment by tobi3988** [comment]
It doesn’t crash if I open it in airplay mode. It crashes after the first request is succesful.

**Comment by fbernutz** [comment]
Oh no! We'll look into this. @mltbnz also experienced a crash, but it couldn't be reproduced a few days later (#365). 
Thanks for reporting this issue!

**Comment by mltbnz** [comment]
> It doesn’t crash if I open it in airplay mode. It crashes after the first request is succesful.

Do you maybe know which request it is? My guess is that the event feature and the criticalmass.in API might have changed and is not versioned. I will investigate that

the response is also different for different user locations

**Comment by mltbnz** [comment]
Might be fixed by #392

**Comment by mltbnz** [comment]
Temporarily you could set the apps language to anything but German. Thanks again for your post. Really helped

**Comment by zeitschlag** [comment]
That `%s` was waaaaay to obvious 🙈  But yes, it works now! Thank you for your help, I'm looking forward to the next release 🙂

**Comment by mltbnz** [comment]
it was and it wasn't 😆 I never used the app in german recently and so I was looking for the error somewhere else. I also added some snapshot tests.
