### ISSUE TITLE
Enabling event notifications does not prompt for permissions

### ISSUE THREAD

**Issue by HippocampusGirl** [criticalmaps/criticalmaps-ios#405]
I just installed the app to get reminded when the critical mass happens. 
However, I never got prompted for notification permissions, even though I activated the feature. This means that I won’t get any notifications, right?

**Comment by mltbnz** [comment]
Hi. The event notification is just happening while the app is in the foreground and no pushes are sent to users. Hope that helps. You can toggle the feature though in the settings.

**Comment by HippocampusGirl** [comment]
Thank you for the clarification!
