### ISSUE TITLE
Changing Event Settings > Event Search Radius does not change radius on map

### ISSUE THREAD

**Issue by foss-** [criticalmaps/criticalmaps-ios#477]
**Describe the bug**
Changing `Event Settings > Event Search Radius` does not change radius on map.

**To Reproduce**
1. Go to `Event Settings > Event Search Radius`
2. change Radius from 5 km to 20 km.

**Expected behavior**
Radius on map remains identical.

 - Device: iPhone XR
 - OS: iOS 16.5
 - Critical Maps 4.2.0

**Comment by mltbnz** [comment]
I think I made a change after we submitted 4.2.0 to the store that fixes exactly this. 

So it should be in the next release which hopefully won't take another year 😄

But it's correct what you submitted. Before I thought the app should only refetch the next ride when it was en/disabled

**Comment by mltbnz** [comment]
So it was actually not fixed. Wrote a test to verify but that failed so I had to create https://github.com/criticalmaps/criticalmaps-ios/pull/482 which fixes it

**Comment by foss-** [comment]
Not seeing a milestone in the PR. Should that be part of 4.2.1 released today? Retried but was still unable to see any change of the radius when changing the setting.

**Comment by mltbnz** [comment]
I have never used milestones here. Release management is a bit more relaxed here.
I am wondering how do you determine if the radius changed? 

I will try to describe the feature as shipped in 4.2.1:
- on the app start and after the first location has been set the next ride will get fetched with the settings that have been loaded from the phone.
e.g. when you saved the radius to be 20km it will send `https://criticalmass.in/api/ride?centerLongitude=13.414251696336253&centerLatitude=52.52253367184523&radius=20&year=2023&month=6`
- after you set the radius to `5 km` it will refetch the next ride like
 `https://criticalmass.in/api/ride?centerLongitude=13.414251696336253&centerLatitude=52.52253367184523&radius=5&year=2023&month=6`

I think what might be missing in the app is that if you start with `20 km` and then set `5 km` for example the event from the `20 km` fetch would not be dismissed from that map although it probably should

**Comment by foss-** [comment]
When I open the map I see a radius on the map, which I assumed would be the radius defined in settings. If I change the radius, the area or radius size never changes. I would expect that visual indicator to adjust according to the altered setting. Or is the circle on the map indicating something different?

**Comment by mltbnz** [comment]
Ah. its that latter.
The radius you see on the map indicates that the map can not show your precise location.
The feature actually does not have any visual representation of the radius though that might be a cool idea

**Comment by foss-** [comment]
So the radius symbolizes the area around the last known location? Hmm, that makes sense, although I am not sure how many users understand a radius as an indicator for lacking GPS.
