### ISSUE TITLE
Chat & Twitter cell paddings

### ISSUE THREAD

**Issue by zutrinken** [criticalmaps/criticalmaps-ios#48]
Chat and Twitter cells don't have the right paddings / margins and font sizes / line height. Defined in [sketch](https://github.com/criticalmaps/criticalmaps-design/tree/master/ios).

### Chat:

*Is:*

![7373765457](https://user-images.githubusercontent.com/888679/52817071-144e7780-30a3-11e9-8fa3-22bd6d6fceb9.png)

*Should:*

![5987654354](https://user-images.githubusercontent.com/888679/52817069-144e7780-30a3-11e9-9b30-99948eb86b10.png)

*Specs:*

> Padding: 16px
> Date: 15px / 16px - Bold #262626
> Margin between date and message: 4px
> Message: 17px / 24px - Regular #45474D

### Twitter:

*Is:*

![211263534654](https://user-images.githubusercontent.com/888679/52817133-495aca00-30a3-11e9-8446-beffc62621fa.png)

*Should:*

![5473652435](https://user-images.githubusercontent.com/888679/52817136-4e1f7e00-30a3-11e9-92d8-e655bf9f23ce.png)

*Specs:*

> Padding: 16px
> Avatar: 40x40px - Inner border: 1px rgba(55,64,82,0.18)
> Margin between avatar and text: 16px
> Name: 15px / 16px - Bold #262626
> Margin between name and username: 4px
> Username: 15px / 16px - Regular #909399
> Date: 13px / 16px - Medium #45474D
> Margin between name and message: 4px
> Message: 17px / 24px - Regular #45474D

**Comment by mltbnz** [comment]
What it looks like now:

<img width="487" alt="Screenshot 2019-04-05 at 09 12 41" src="https://user-images.githubusercontent.com/14075359/55610353-0a7ff100-5783-11e9-8671-039bc9bbdbe5.png">
<img width="487" alt="Screenshot 2019-04-05 at 09 12 13" src="https://user-images.githubusercontent.com/14075359/55610354-0a7ff100-5783-11e9-8fd4-94216d213cb6.png">

Question @zutrinken
Can you point out what is still missing?

**Comment by zutrinken** [comment]
Text size, weight, color, margins, border, ... https://zpl.io/bzNgGZl

![635453](https://user-images.githubusercontent.com/888679/55617329-1cb65b00-5794-11e9-87eb-5d878ac946d0.png)

![234242](https://user-images.githubusercontent.com/888679/55617330-1cb65b00-5794-11e9-8238-2e6cb7f26caf.png)
