### ISSUE TITLE
Use GeoJson on the map

### ISSUE THREAD

**Issue by paulop33** [criticalmaps/criticalmaps-ios#485]
Hi everyone,

I'm Paul, a french web developer and a member of the @velo-cite association too.
This weekend, we organise our first "convergence".
The convergence is like a critical mass but with several starts in differents cities. We start on different places but arrive to the same park to do the last kilometer together.
You might have a look to our website (in french sorry : http://tousavelo.velo-cite.org/) or directly to the map to understand. 

![Capture d’écran du 2023-06-16 15-52-36](https://github.com/criticalmaps/criticalmaps-ios/assets/3404409/6373391c-3923-4e2f-b3e7-71026dc3957a)

I think CM could display all the "paths".
I don't think the gpx file can be used for that.
CM should be able to load a GeoJson file to display all of them.

What do you think about it ?
Thanks for this great app' !

Paul

**Comment by genevievecory** [comment]
Are you wanting what CriticalSnake does?  https://github.com/weliveindetail/CriticalSnake - records the ride and displays it.  

Or do you mean loading up a GPX file **before** the ride so people can see it in CM?

**Comment by paulop33** [comment]
I would like to display all the path before all the parallel rides. 
I think the GPX contains only one ride

**Comment by mltbnz** [comment]
Hey. I'm also not quite sure if I fully understood your proposal.

Are you suggesting that users can load a local file that contains a route into their CM app? 

Or do you mean a recording functionality? Because I thought about that recently too 😄

Btw I think `gpx` files can also be a container for a multiple points

**Comment by paulop33** [comment]
Hey, thanks for your quick replies,

I'm suggesting that users can load a local file that contains several paths (even path where they don't go).
In the case of our convergence, some people start on the east (Libourne, the yellow path), other starts on Talence (South, red) and ect.
We didn't take the same road. If you're on the north, you take the blue path and you should'nt have to go to a path in another color.

We only done a final kilometer together (in the center of the map) which in not on my picture.


I'm going to check the `gpx` documentation.
And no, I'm not looking for records :)
