### ISSUE TITLE
Location tracking at all times

### ISSUE THREAD

**Issue by 343max** [criticalmaps/criticalmaps-ios#506]
**Describe the bug**
The app is tracking my location in the background even when I'm in Beobachtermodus

**To Reproduce**
1. Launch the app
2. Turn on Beobachtermodus
3. go to the Home Screen
4. see the app is still tracking the users location

**Expected behavior**
The app shouldn't track my location when it's in the background ä

**Desktop (please complete the following information):**
 - OS: ios

**Smartphone (please complete the following information):**
 - Device: iPhone 15

**Comment by mltbnz** [comment]
Thanks for submitting the issue. 
Seems so indeed. I think I haven't thought of that. 
Will do a fix asap

**Comment by 343max** [comment]
I'm happy to have a look and submit a PR if you don't have time.

**Comment by mltbnz** [comment]
Would be great of course!

**Comment by mltbnz** [comment]
We released 4.5.0 which fixes this issue. 

Will go ahead and close it
