### ISSUE TITLE
Question: Deployment target 

### ISSUE THREAD

**Issue by mltbnz** [criticalmaps/criticalmaps-ios#52]
Hi. I just discovered this repo and would like to participate.
I would like to know if there is a reason that the the deployment target is iOS 8.0?

I think the codebase could benefit from even little things like StackViews.
Regards

**Comment by lennet** [comment]
Hey, that's a great question. 

I totally agree that we should raise the deployment target at least to iOS 9 as it is supported for all devices that can run iOS 8.

In general, I prefer having a minimum deployment target and providing basic support for as many devices and versions as possible and use #available for features that requires newer apis if its not too much work to maintain. 

What do you think? Are there any APIs that require iOS 10 or later that you would like to use?

**Comment by headione** [comment]
imo, i also think we could drop iOS 8 target because it's rarely used afaik and it can help with cleaner code because less #available conditions will be needed. but i'm fine with both targets - whatever helps for maintaining and scaling the product 👍

**Comment by mltbnz** [comment]
Just went back to this:
https://mixpanel.com/trends/#report/ios_12

So I'll do a PR that will raise the target to iOS 10.
