### ISSUE TITLE
SegmentedControl in SocialViewController slipping under Toolbar in iOS <11.0

### ISSUE THREAD

**Issue by mltbnz** [criticalmaps/criticalmaps-ios#53]
Looks like the segmentedControl hides under the toolbar for example on iOS 10.3.1
<img width="432" alt="Screenshot 2019-03-12 at 16 06 26" src="https://user-images.githubusercontent.com/14075359/54219375-a9e8f580-44ef-11e9-9776-4792457a2899.png">

**Comment by mltbnz** [comment]
also breaks in settings. But maybe a seperate issue
<img width="432" alt="Screenshot 2019-04-04 at 15 32 41" src="https://user-images.githubusercontent.com/14075359/55560110-d90a1580-56ef-11e9-8100-ffcf2f4e949e.png">

**Comment by lennet** [comment]
that is a different issue. I send out a pr for that one #65
