### ISSUE TITLE
Version and Build Number in Settings

### ISSUE THREAD

**Issue by zutrinken** [criticalmaps/criticalmaps-ios#55]
Add the Artwork, version and build number to settings.

_Any other information to show here?_

![346456354](https://user-images.githubusercontent.com/888679/54755912-62492480-4be7-11e9-8870-92fcf9629a9a.png)

**Comment by stephanlindauer** [comment]
maybe the build date :man_shrugging:

**Comment by mltbnz** [comment]
I have a branch where the build and versionnumber is also displayed under the system settings. Main reason tough was to add acknowledgements for 3rd party. I think I could easily add a cell in the apps settings too but would also like to merge that other feature. Sound good or does that go beyond the scope? https://github.com/mltbnz/criticalmaps-ios/tree/settings

<img width="390" alt="Screenshot 2019-03-27 at 20 56 01" src="https://user-images.githubusercontent.com/14075359/55107950-c92c7900-50d2-11e9-80ed-49407a7b74e5.png">

**Comment by zutrinken** [comment]
Sounds great!
