### ISSUE TITLE
Chat input disappears when switch to emoji keyboard

### ISSUE THREAD

**Issue by zutrinken** [criticalmaps/criticalmaps-ios#72]
Switch keyboard to emoji, the chat input moves to the bottom behind the keyboard.

<img src="https://user-images.githubusercontent.com/888679/55979512-9cf82700-5c92-11e9-9432-fa7b64f9ab4f.PNG" width="375" />

**Comment by mltbnz** [comment]
Works for me. 
What iOS Version do you use?

**Comment by zutrinken** [comment]
iOS 12.2 on iPhone 8
