### ISSUE TITLE
SettingsFooterView uses deprecated API

### ISSUE THREAD

**Issue by lennet** [criticalmaps/criticalmaps-ios#76]
"Setting the background color on UITableViewHeaderFooterView has been deprecated. Please set a custom UIView with your desired background color to the backgroundView property instead."

**Comment by lennet** [comment]
Seems like this warning regressed with #69

**Comment by lennet** [comment]
<img width="882" alt="Bildschirmfoto 2019-09-30 um 14 02 39" src="https://user-images.githubusercontent.com/7677738/65877033-f8c28380-e38a-11e9-9ff1-102bb03405d2.png">

The background Color doesn't work anymore on iOS 13. We need to replace it with a custom backgroundView

**Comment by maxxx777** [comment]
What is the current state of the issue? I can not see any warnings regarding `UITableViewHeaderFooterView` in Xcode 11. The background color in `SettingsFooterView` looks correct in both light and dark modes in iOS 13.
