### ISSUE TITLE
UI Tests 

### ISSUE THREAD

**Issue by lennet** [criticalmaps/criticalmaps-ios#84]
It would be nice to have a infrastructure for UI tests. We could use that for testing but also screenshot to have a quick overview how the app looks like in different languages and device types

**Comment by lennet** [comment]
Could also be interesting to use UI tests for the new performance metrics introduced with Xcode 11

**Comment by fbernutz** [comment]
Hi, I would like to help you with this. 

My plan would be: 
- Use `fastlane` to make screenshots from every screen.
- Add a UITests Target with _one_ UITest which navigates through the application and calls `snapshot` on every screen. 
- Add configurations to make screenshots in every language and with some different devices

This would create the foundation and you could add more UITests which actually test something if you want to. _(But I really love Snapshot Testing and am excited to have them included in this project hopefully, see #136. I don't think you need more than this one UITest which tests whether all screens are actually reachable)_

Do you think something is missing or I should take another approach for this issue?

**Comment by fbernutz** [comment]
Therefore I need to check in the configured Schemes. So, I can configure if fastlane should run the unit tests or the UI Tests. Would this be okay for you, because you ignore the whole .xcodeproj at the moment?

**Comment by lennet** [comment]
Thanks for supporting us! 

Your plan looks great!

 I think having UITests will become even more useful once we move our Friends feature branch (#96) into master branch because it contains some logic and flows which could be tested with UITests

I think checking in Schemes should be okay. I'm not 100% sure why we currently have the full .xcodeproj in gitignore but we can definitely change that!
