### ISSUE TITLE
Friends

### ISSUE THREAD

**Issue by lennet** [criticalmaps/criticalmaps-ios#96]
Open Questions/Tasks
- [x] Verification (Signature?)
- [x] Verification caching
- [x] Maps UI
- [x] Settings UI
- [x] Storage
- [ ] documentation

**Comment by lennet** [comment]
related to https://github.com/criticalmaps/criticalmaps-android/issues/119

**Comment by zutrinken** [comment]
There is a UI suggestion in the iOS design files (last two screen on the right): <img src="https://raw.githubusercontent.com/criticalmaps/criticalmaps-design/master/ios/critical-maps-app-preview.png" />

But that's not based on the latest technical constraints we discussed. So for a UI concept we first need a description on how the feature can be technically implemented.

**Comment by lennet** [comment]
Yeah we still don't really decided what we'll do. I'll start implementing the settings ui based on the code I already have

**Comment by lennet** [comment]
@zutrinken How about adding an empty state view/ message for users that don't have friends connected yet. Maybe a small explanation 
<img width="584" alt="Bildschirmfoto 2019-09-23 um 22 06 58" src="https://user-images.githubusercontent.com/7677738/65458698-7992f400-de4e-11e9-87bb-7cc8e90f6c06.png">

**Comment by maxxx777** [comment]
Would love to see this feature in the app. 
What is the current state of the implementation? 
If I can help with the feature, please let me know.

**Comment by lennet** [comment]
We have a feature branch (`friends`) for that  with a fully working version of that feature however it's not ready for production yet. 


There are some things to be done 
1. The Map overlays need to be updated to support displaying names 
<img width="504" alt="Bildschirmfoto 2019-10-06 um 17 52 08" src="https://user-images.githubusercontent.com/7677738/66271734-059b1780-e862-11e9-82b2-89feea3843b1.png">
The full design specs are available in our design repo https://github.com/criticalmaps/criticalmaps-design

2. We are not 100% sure how we should do the the friends recognition with our current API. We are currently renewing the users id every 24 hours for privacy reasons which makes it hard to recognise people (which is also the purpose of that :D). There are some possible options 
- Don't renew the id for some days/ weeks which makes people auto expiring and also everyone could track users over multiple days as long as their using the friends feature
- Sign the id with an key and share the key for verifying the signature with your friends so that your Id can change and friends need to verify the signature (This method is currently implemented in the feature branch). This is comes with some overhead as a users needs to try verifying the signature for every id on the map as long as they haven't found their friends. 
- Instead signing the id, we could hash a secret with the current day (in UTC) and share the secret with your friends. That has similar benefits as signing the id but doesn't require checking every id because we know exactly with id we are expecting for a certain day as long as users didn't change their time manually.

3. The android implementation isn't done yet. The current state can be seen here https://github.com/criticalmaps/criticalmaps-android/issues/119 .

**Comment by lennet** [comment]
Added separate issues for open tasks to have a better overview about the remaining work 
#164 #163 #162

**Comment by fbernutz** [comment]
The Friends Feature is hidden behind a Feature Toggle and available on `master`. To use this Feature, go to `Feature.swift` and change this:

```swift
private var currentState: [Feature: Bool] = [
    .friends: true
]
```

All other open issues should be handled in separate issues, so I'll close this now.
